[mypy]
python_version = 3.12
strict = True
warn_unused_configs = False
ignore_missing_imports = False

[mypy-tests.*]
ignore_errors = True

[mypy-pgvector.*]
ignore_missing_imports = True

[mypy-docling.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-readability.*]
ignore_missing_imports = True
